repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        name: Sort imports
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: black
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
# vim: ts=2 sw=2
